### ISSUE TITLE
Any documentation about the ewelink api directly(not the package) ?

### ISSUE THREAD

**Issue by becrespi** [skydiver/ewelink-api#102]
Hello !

It’s maybe a bit off topic, but does someone know if any kind of documentation on the ewelink API has been made ?

I need to implement the control of ewelink connected devices from scratch and I don’t find any resources that simply explain how this API works.

Thank you in advance

**Comment by bwp91** [comment]
https://github.com/CoolKit-Technologies/apiDocs/tree/master/en

In particular APICenterV2.md

**Comment by becrespi** [comment]
Thanks a lot !
