### ISSUE TITLE
Error 503 Service

### ISSUE THREAD

**Issue by vmagalhaes** [skydiver/ewelink-api#103]
Hey!

In the last few days, the server looks strange, I'm getting this error at some methods:
`{ error: 503, msg: undefined }`

Are happening with you too?

**Comment by cristiancporto** [comment]
> Hey!
> 
> In the last few days, the server looks strange, I'm getting this error at some methods:
> `{ error: 503, msg: undefined }`
> 
> Are happening with you too?

I'm getting a FetchError `'invalid json response body at https://us-api.coolkit.cc:8080/api/user/device/status reason: Unexpected token < in JSON at position 0'` sometimes in the last few weeks... Not the same, but maybe related?

**Comment by vmagalhaes** [comment]
> > Hey!
> > In the last few days, the server looks strange, I'm getting this error at some methods:
> > `{ error: 503, msg: undefined }`
> > Are happening with you too?
> 
> I'm getting a FetchError `'invalid json response body at https://us-api.coolkit.cc:8080/api/user/device/status reason: Unexpected token < in JSON at position 0'` sometimes in the last few weeks... Not the same, but maybe related?

Yeh, same with me, I changed to branch release/3.1.0 and change the method to setWSPowerState

**Comment by vmagalhaes** [comment]
https://github.com/skydiver/ewelink-api/issues/89 @cristiancporto
