### ISSUE TITLE
I cant connect websocket, and power on , off dont work

### ISSUE THREAD

**Issue by apadilla83** [skydiver/ewelink-api#115]
Since Yesterday   I cant connect websocket, and power on , off dont work. But i can get status of devices, and discover etc..

When I connect on websocket get this:

10/29/2020 08:00:36:   error: 400,
10/29/2020 08:00:36:   reason: 'Bad Request',

Wen I power on Device I get the normal request:
10/29/2020 08:25:01: { status: 'ok', state: 'on' }

But device dont power on.

Thanks

**Comment by foulek57** [comment]
Hi,

Just Update to last version
Since yesterday the "old" API send a bad request.

**Comment by apadilla83** [comment]
> Hi,
> 
> Just Update to last version
> Since yesterday the "old" API send a bad request.

ok Many thanks just work now!

**Comment by foulek57** [comment]
Great, so please close the issue 😉
