### ISSUE TITLE
List of Regions

### ISSUE THREAD

**Issue by inayatu** [skydiver/ewelink-api#129]
There should be new feature which would **list down all the available 2 letter region name** provided and supported by ewelink.  I had hard time finding mine.

**Comment by jamesgstone** [comment]
Interface domain name
Mainland China: https://cn-apia.coolkit.cn
Asia: https://as-apia.coolkit.cc
Americas: https://us-apia.coolkit.cc
Europe: https://eu-apia.coolkit.cc
Note: The domain name for China (mainland) is .cn , The domain name of other regions is .cc

**Comment by murfett-au** [comment]
The region is used to generate an the eWeLink API endpoint to use. The `getApiUrl()` function generates this:

```
getApiUrl() {
  return `https://${this.region}-api.coolkit.cc:8080/api`;
}
```

I wrote a script to resolve each 2 letter region url in DNS, and the following were the valid regions as of 2024-11-26:


Hence the 2 character region code must enable the getApiUtl to create a valid URL. As far as I could see, the valid regions are (along with which region the AWS API running this is):
`as` - Asia (as-api-elb-953210114.ap-southeast-1.elb.amazonaws.com);
`cn` - China (cn-api-elb-146274557.cn-north-1.elb.amazonaws.com.cn);
`us` - America (us-api-elb-227413280.us-west-1.elb.amazonaws.com);
`eu` - Europe (eu-api-elb-1968000189.eu-central-1.elb.amazonaws.com);
`ir` - Iran (ir-vps.coolkit.cc);

If you want to check if your country is a valid region, you can prefix it before `-api.coolkit.cc` and ping it. If there is not a host named `${region}-api.coolkit.cc`, it is not a valid region - except China, which uses [cn-apia.coolkit.cn](https://cn-apia.coolkit.cn/) - and this region will not work in this repo, I think, as it does not replace the .cc with .cn tld
