### ISSUE TITLE
Slow login. Using ewelink-api is much slower than using ewelink app on mobile.

### ISSUE THREAD

**Issue by ttz642** [skydiver/ewelink-api#27]
Not so much of an issue but an observation and a request to update the documentation.

What I have found is that when I use ewelink-api to access the devices via the cloud it takes a long time to open and fetch information about the devices, eg:
`	connection = new ewelink({`
`		email: config.ewelink.email,`
`		password: config.ewelink.password`
`	});`
`. . .`
`	devices = await connection.getDevices();`
`	console.log(devices);`

Running this takes nearly 6 seconds (and longer sometimes):
`$ time bin/fetchDevices.js`
`real	0m5.816s`
`user 0m1.349s`
`sys	0m0.084s`

Occasionally it failed to connect and I noticed that the host it was trying to connect to was the US server, ie:
`https://us-api.coolkit.cc:8080`

This made me think, what if this is the default login is the us server so I changed the Class Instantiation to include my region:
`	connection = new ewelink({`
`		email: config.ewelink.email,`
`		password: config.ewelink.password,`
`		region: "eu"`
`	});`

sure enough:
`$ time bin/fetchDevices.js`
`real	0m1.930s`
`user	0m1.331s`
`sys	0m0.088s`

Could you update the documentation to require the region be included in the Class Instantiation API as it affects performance.

This is also why I think the alternative connection is failing as they are sometimes connecting to the wrong server for where a user is registered. ie add the region as a required parameter when using the 'access token' or 'api key'.

Only had a switch and socket a few days but so far I've had more success with your library than all the others I've tried, I just want a simple library not a whole automation system.

I noticed you've commented on LAN mode which is what I'm really after, I'll start moving that way soon as I'd rather not be using the cloud to store what's happening in my house and I want it to work when the internet is down.

pinging US server:
`$ ping -c 10 us-api.coolkit.cc`
`PING us-api.coolkit.cc (13.57.86.90) 56(84) bytes of data.`
`64 bytes from ec2-13-57-86-90.us-west-1.compute.amazonaws.com (13.57.86.90): icmp_seq=1 ttl=35 time=163 ms`
`. . .`
`--- us-api.coolkit.cc ping statistics ---`
`10 packets transmitted, 10 received, 0% packet loss, time 9009ms`
`rtt min/avg/max/mdev = 162.212/165.930/177.053/4.508 ms`

pinging EU server:
`$ ping -c 10 eu-api.coolkit.cc`
`PING eu-api.coolkit.cc (52.57.118.192) 56(84) bytes of data.`
`64 bytes from ec2-52-57-118-192.eu-central-1.compute.amazonaws.com (52.57.118.192): icmp_seq=1 ttl=41 time=41.5 ms`
`. . .`
`--- eu-api.coolkit.cc ping statistics ---`
`10 packets transmitted, 10 received, 0% packet loss, time 9013ms`
`rtt min/avg/max/mdev = 39.034/42.012/43.908/1.710 ms`

**Comment by skydiver** [comment]
Hello @ttz642 

You're right, by default is connecting to us server.

So, first thing is to update documentation to specific you need to set your region and leave empty in case of not knowing.

I never had troubles like people are reporting on #21, probably because i'm on `us` region.

Conclusion, you need to set region ever, specially if you're connecting with api key and token.


The second part, the lan mode.

There are a couple of PRs open for this feature, but the original author didn't respond on the last weeks.

I will try to push this changes to include on next weeks.

**Comment by ttz642** [comment]
Martin,
> The second part, the lan mode.
> There are a couple of PRs open for this feature, but the original author didn't respond on the last weeks.
> I will try to push this changes to include on next weeks.

I will test / debug . . .

-- 
Steve

**Comment by skydiver** [comment]
Hello @ttz642 

Docs where updated, here are the list of pages who have changed:

* quickstart
* class-instantiation
* demos/node
* demos/serverless

Would be great if you can take a look and let me know if i missed something.


Thanks.-

**Comment by ttz642** [comment]
Martin,
> * quickstart
> * class-instantiation

For consistency could you change quickstart to use connection as all other sections of the documentation use rather then being different and using conn?

Also could you add the warning you have in:
- class-instantiation
- demos/serverless
to:
- quickstart
- demos/node

Also perhaps change the demos/serverless examples to use the region returned from the login for the subsequent access using accesstoken and apikey, ie:

- const region = login.region;

Otherwise looks good.

-- 
Steve

**Comment by skydiver** [comment]
Docs where updated.

Thanks @ttz642 for your feedback.

**Comment by ttz642** [comment]
Martin,
> Docs where updated.

One last minor suggestion, perhaps add:

`    console.log('region: ', login.region);`

to the login method so it's the same as the serverless demo.

**Comment by doganbulut** [comment]
Hi,
I am using ewelink-api.
I've used the toggle function five times in a row.
It works between five and six seconds. Is this normal ?

ok1 Fri Jan 03 2020 21:52:52 GMT+0300 (GMT+03:00)
ok2 Fri Jan 03 2020 21:52:56 GMT+0300 (GMT+03:00)
ok3 Fri Jan 03 2020 21:53:01 GMT+0300 (GMT+03:00)
ok4 Fri Jan 03 2020 21:53:05 GMT+0300 (GMT+03:00)
ok5 Fri Jan 03 2020 21:53:10 GMT+0300 (GMT+03:00)

![case1](https://user-images.githubusercontent.com/4948063/71743154-d9009700-2e74-11ea-8c4a-c9c141a28ef9.PNG)

**Comment by ttz642** [comment]
> Hi,
> I am using ewelink-api.
> I've used the toggle function five times in a row.
> It works between five and six seconds. Is this normal ?
I experienced it at ~ 6s and got it down to ~ 2s. I think there are some tweaks needed for the performance of the code.

Have you got the correct region ? See issue #53 I'm guessing GMT+3 you should be using eu, see what gets returned. Call class instantiation with no region and the getCredentials, see: https://ewelink-api.now.sh/docs/class-instantiation

After migrating to the 2.0 code I might have a look at it.

**Comment by jmarfia** [comment]
I'm in south america, the app works instantaneously, but the API takes up to 15-20 secs to toggle on/off any device. Im using the correct region. Also, i tried with the other regions, and no better results... any advice to get lower delay?

**Comment by ttz642** [comment]
> I'm in south america, the app works instantaneously, but the API takes up to 15-20 secs to toggle on/off any device. Im using the correct region. Also, i tried with other regions, and no better results... any advice to get lower delay?

Do you log in each time or have you got an application running which only logs in once?

**Comment by jmarfia** [comment]
> > I'm in south america, the app works instantaneously, but the API takes up to 15-20 secs to toggle on/off any device. Im using the correct region. Also, i tried with other regions, and no better results... any advice to get lower delay?
> 
> Do you log in each time or have you got an application running which only logs in once?

I login each time. How can i let the session open?

**Comment by ttz642** [comment]
I've split my application into services that run constantly and thus only connect once, or reconnect on error.

www - operator interface to control panel to show/change state of devices & edit switching table
events - captures events from the devices (via the cloud at the moment, looking to implement over LAN)
lanSwitcher - process to change device state
scheduler - changes device state according to the switching table which has state of devices over complete day in 5 min slots

I use REST (ie web services) to send messages between services.

Might package up one day and upload to github when I get the time.

**Comment by skydiver** [comment]
Hey @jmarfia 

You can try to get your access token and api key and use instead of login with user/pass all the time.

First, get your credentials: https://github.com/skydiver/ewelink-api/blob/master/docs/available-methods/getcredentials.md

Initialize the class using `at` and `apiKey`: https://github.com/skydiver/ewelink-api/blob/master/docs/class-instantiation.md

Get your device as usual: https://github.com/skydiver/ewelink-api/blob/master/docs/available-methods/getdevice.md
