### ISSUE TITLE
documentation update

### ISSUE THREAD

**Issue by ttz642** [skydiver/ewelink-api#29]
Martin,

Issue #21 is really due to misunderstanding of the documentation.

Perhaps a few more clarifications to address this.

**Login method add:**
`console.log('Region: ', auth.region);`

**serverless**
Need to put code in async function because if you just copy and paste it doesn't work.

**Introduction**
_Make a note that the region assigned when your eWeLink account is initially created may not be what you expect and you should check by what server/region with either **login** or **getRegion** return._

**Comment by skydiver** [comment]
Thanks for the suggestions @ttz642 

Added your feedback to the documentation.

Will wait a little more before modify the introduction.
