### ISSUE TITLE
documentation:: Class Instantiation

### ISSUE THREAD

**Issue by ttz642** [skydiver/ewelink-api#31]
If I try another connection using region & access token:
```
	const atConnection = new ewelink({
		at: login.at,
		region: login.region
	});
```
using the connection to openWebSocket ALWAYS fails with the error:

`openWebSocket data:: { error: 406, sequence: '1573811728283' }`

If I add the apiKey (obtained from the first device from the getDevices()):
```
	const atConnection = new ewelink({
		at: login.at,
		apiKey: login.user.apikey,
		region: login.region
	});
```
it works.

Thought: you mentioned a double login where the us is tried first and then the region, would the apikey be picked up on the first access (ie us server) and not updated on second login to the regional server and therefore use the wrong apikey provided by the us server?

**Comment by skydiver** [comment]
Hey @ttz642 

I believe the documentation is confusing about when to use `apikey` and when not.

So, i think we need to remove the code example using just `at` and `region` and prevent future confusions.

Thoughts?

**Comment by ttz642** [comment]
Agree...

**Comment by ReneMarquez** [comment]
> Hey @ttz642
> 
> I believe the documentation is confusing about when to use `apikey` and when not.
> 
> So, i think we need to remove the code example using just `at` and `region` and prevent future confusions.
> 
> Thoughts?

what does the 406 error mean? I'm also getting this, so I'd just like to know if its a credentials/auth

**Comment by ttz642** [comment]
Add to Documentation suggestions/feedback (issue #35 )

**Comment by ttz642** [comment]
Added to Documentation suggestions/feedback (issue #35 ).
