### ISSUE TITLE
Minor documentation issue :: typo in Demos / serverless

### ISSUE THREAD

**Issue by ttz642** [skydiver/ewelink-api#32]
Martin, just to make sure cut'n'paste works for all examples.

Each time you make a Class Instantiation the structure is missing the comma on the first line and unnecessarily includes one on the second, eg:
```
  const newConnection = new ewelink({
    at: accessToken
    region: region,
  });
```
should be written:
```
  const newConnection = new ewelink({
    at: accessToken,
    region: region
  });
```
This is the case of all three examples in serverless demo

**Comment by skydiver** [comment]
Thanks @ttz642 

Will close this one, but will open a new ticket for docs suggestions.
