### ISSUE TITLE
RENAME login to getCredentials or getAccount ?

### ISSUE THREAD

**Issue by ttz642** [skydiver/ewelink-api#33]
Martin,

The method login is confusing, it isn't actually logging in and does not require any information to LOGIN.

Everybody understands the term login to mean gaining secure access to something by supplying account or other secret information.

Login is really fetching the details about the current session, perhaps it would be better if it were renamed to getCredentials (or getAccount) which more correctly identifies what it is actually doing.

Rather than simply rename and break everybody's code perhaps create a new method getCredentials (or getAccount) (a duplicate of login) and just mark login as:

_login has been DEPRECATED and will be removed in the near future, please update your code to use getCredentials (or getAccount)_

Perhaps with release 2.0.0, version with  LAN access tried and tested ?

-- 
Steve

**Comment by skydiver** [comment]
I agree with you @ttz642 

My plan will be:

1. create `getCredentials` and keep login as an alias
2. add `getCredentials` to docs site
3. update `login` docs, saying is deprecated and you should use `getCredentials`
4. update `openWebSocket` method to call `getCredentials` if needed

I agree on the plan for 2.0, LAN mode should be released and `login` method can be deleted.

**Comment by ttz642** [comment]
Has been added to 1.10.0
