### ISSUE TITLE
Documentation suggestions/feedback

### ISSUE THREAD

**Issue by skydiver** [skydiver/ewelink-api#35]
Here you can post your suggestions/feedback for the [docs site](https://ewelink-api.now.sh/docs/demos/serverless)?

**Comment by ttz642** [comment]
**openWebSocket**

Make sure `.close()` is called before application terminates otherwise restarting application may not connect 1st time.

In main application I have:

```
var socket;	//define outside of async function to allow access as required
process.on("SIGINT", () => {
	console.log(" - Caught SIGINT. Exiting in 3 seconds.");
	console.log("Closing WebSocket...");
	var cls = socket.close();
	setTimeout(() => {
		process.exit(0);
	}, 3000);
});
```
So if the process is terminated it will close the web socket. Since adding this the app has gracefully closed the socket every time and always restarts 1st time.



```
var date = new Date();

(async () {
	// login credentials required BEFORE using openWebSocket()
	if(vers < "1.10.0"){//pseudo code !
		const login = await connection.login();
	}else{
		const login = await connection.getCredentials();					//.login() DEPRECATED
	}
	socket = await connection.openWebSocket(async data => {
		if(data == "pong"){//can just ignore of for debug print date & time to console
			date = new Date();
			console.log("keepalive received at:",date.toUTCString());
		}else{//process event...
			console.log("openWebSocket data::",JSON.stringify(data,null,4));	//if(DEBUG) when coded !
		}
	});
})();
```

**Comment by ttz642** [comment]
Move documentation from external site to the README.md file so documentation can be updated as part of new release / branch.

**Comment by ttz642** [comment]
The definition for getRegion is missing from index.d.ts

Closed #34

**Comment by ttz642** [comment]
Class Instantiation (see #31 for background).

```
	const atConnection = new ewelink({
		at: login.at,
		apiKey: login.user.apikey,
		region: login.region
	});
```

**Comment by peperoca116** [comment]
Hi, the api works great! No issues found!
I will like to know if there is an "easy" way to get the following parameters from the power measuring devices:  1. Voltage,  2. Current, 3. Power

I have a turn around where i open a socket, ask for the device status and after that the socket starts receiving data (V / C / P) when the sonoff sends information. This is ok. I was just wondering if there is an easy way to get this data with a special request/command. E.g. 

Awesome work. Thanks in advance for your response.

**Comment by ttz642** [comment]
Need to include more details about the region in the [class instantiation](https://ewelink-api.now.sh/docs/class-instantiation), see issues #53, #27, #47

It is causing many issues and would be best dealt with by more details in the class instantiation.
