### ISSUE TITLE
Can this work with just javascipt, without Node?

### ISSUE THREAD

**Issue by primalnow** [skydiver/ewelink-api#40]
This is not an issue. Just a question/wish.

Is it possible to use this script from vanilla javascript, without using Node?

**Comment by skydiver** [comment]
Are you talking on a browser?

**Comment by primalnow** [comment]
Yes.  In a browser.

**Comment by skydiver** [comment]
Yes, but you need to use something like webpack.

I was able to use the library with nuxtjs and nextjs.

**Comment by faisal-qureshi** [comment]
This can be closed
