### ISSUE TITLE
Change color ?

### ISSUE THREAD

**Issue by foulek57** [skydiver/ewelink-api#43]
Hi, 

I try to change a color of a humidifier with led color, here the params of the device :

`params: {
lightBcolor: 0,
rssi: -50,
staMac: '2C:3A:E8:45:82:25',
lightRcolor: 255,
timers: [Array],
lightswitch: 0,
water: 1,
lightGcolor: 0,
switch: 'off',
lightmode: 1,
lightbright: 100,
fwVersion: '2.7.0',
state: 2,
sledOnline: 'on'
},
`
They are a possibility to change this data ?

Thanks

**Comment by skydiver** [comment]
Hello @foulek57 

I don't have access to this device so i can't answer your question.

Hope someone else can help with your question.

**Comment by ttz642** [comment]
Is it possible to change the color of light switches?

In bedroom it would be better if off color were pink and on blue. Easier to sleep.

**Comment by foulek57** [comment]
Hello,

I think have find a way, will do some test and come back to you

**Comment by foulek57** [comment]
Hello, 

Have fins a way ans it's work !
Juste need to send over thé socket the json with the value at each color red green blue.
Possible to include it in your code ? 
I can give you the complet json I send

**Comment by ttz642** [comment]
foulek57, post the json.

I'm guessing it makes sense to create a new method to configure devices, ie:

- setDeviceConfig()

**Comment by foulek57** [comment]
Hello, 

I don't know if they are the same params on all lighting I need the results of getdevice of the LED strip to compare

**Comment by foulek57** [comment]
Here the script I used for, note that I run it with a server and send my request with a http request

`app.get('/wi16/:device_id/:apikey/:r/:g/:b/:lb', function(req, res) 
          {
            (
              async () => 
                {
                  var device_id = req.params.device_id;
                  var apikey = req.params.apikey;
                  var r = req.params.r;
                  var g = req.params.g;
                  var b = req.params.b;
                  var lb = req.params.lb;

                  const timeStamp = new Date() / 1000;
                  const sequence = Math.floor(timeStamp * 1000);
                  var payload = {};
                  payload.action = 'update';
                  payload.userAgent = 'app';
                  payload.apikey = '' + apikey;
                  payload.deviceid = '' + device_id; 
                  payload.params = {};
                  payload.params.lightBcolor = b; // 0-255
                  payload.params.lightRcolor = r;
                  payload.params.lightGcolor = g;
                  payload.params.lightbright = lb; // 0-100%
                  payload.sequence = '' + sequence; 
                  var string = JSON.stringify(payload);
                  console.log(string);
                  res.send(string);
                  socket.send(string);
                }
            )();
            }); `

Have it in the async function of the socket.
