### ISSUE TITLE
Error 503

### ISSUE THREAD

**Issue by Fakkio** [skydiver/ewelink-api#45]
For a few days now, when I try to log in, I get the following error: `Service 503 temporarily unavailable` and a CORS error.
Does it just happen to me? Any solutions?

**Comment by ttz642** [comment]
What function call was this returned by?

I'm guessing the server was down.

Generic HTML definition of error 503:
> The 503 Service Unavailable error is an HTTP status code that means the website's server is simply not available right now. Most of the time, it occurs because the server is too busy or because there's maintenance being performed on it.

**Comment by Fakkio** [comment]
yes, I thought so, but I still get that error for days.
I'm simply doing this, in a react hook:
```
React.useEffect(() => {
  const newConnection = new ewelink({
    email: "<myEmail>",
    password: "<myPass>",
    region: "eu"
  });
  newConnection.login();
  setConnection(newConnection);
}, []);
```
All this worked until few days ago.
Thanks,
Fakkio.

**Comment by skydiver** [comment]
@Fakkio probably your browser is blocking the request to a different domain
try with a simple node script to confirm is not the server or your credentials

**Comment by Fakkio** [comment]
Ok, i'll try with a node script. I don't get why this did work until few days ago.

**Comment by Fakkio** [comment]
Hi, I confirm: in node it works like a charm! Any idea what can I do to make it work in the browser?

**Comment by skydiver** [comment]
@Fakkio not sure if ewelink changed his CORS policy/config in the last few days or what ...
you can always make the requests to ewelink servers through your backend where CORS will not be a problem

**Comment by Fakkio** [comment]
@skydiver I think so, they must have changed CORS policy for some reason. Unfortunately, my back end is in C#, and I cannot use this library, neither I found one for that language.
For the moment I'll use https://cors-anywhere.herokuapp.com/ and then I'll decide what to do.
Thank you, I think we can close here.

**Comment by DatStorm** [comment]
@Fakkio how did you do that? Have the same problem in my react application.
