### ISSUE TITLE
401 "Authentication error" 

### ISSUE THREAD

**Issue by scInvest** [skydiver/ewelink-api#48]
I'm writing application to control my devices, from a web browser, and I'm randomly unable to connect to you api.
I'm using the connection object following your examples, and I'm getting error 401 "Authentication error", as a result of getDevices or setDevicePowerState. Function like getDevicePowerState or getRegion, works as expected. It's happened over and over again, on the same machine. While the same code on the same time other machine works fine. Weblink application also works.
The issue is reproducible on my local machine, and azure server.
Calling api from different location(probably) is not the source off issue, because i swich devices only when i'm forced to do it.

It's a serious issue because it's made your API impossible to use and trust.

**Comment by ttz642** [comment]
I've also experienced some connection issue.

The server only allows one log in at a time so connecting from another device may interrupt the other connection. Need a shorter timeout on the services and need an auto re-connect or error notification.

When something goes wrong there isn't a timely notice of an error, it can take perhaps 20 minutes to timeout (eg when internet is disconnected).

Personally I think the local access is the way to go and I intend to only connect to he server to register devices (until we have local registration server).

I've been writing a web dashboard and when I get time I'll migrate to the release 2.0.0 and use the local access.

I found the best and most stable way was to have a single threaded web server connecting to the sonoff server and passing everything through it. I have a process connected to the sonoff server listening for events and it posts them to my web server.

**Comment by ttz642** [comment]
Running my webserver connected to the sonoff cloud I get timeouts which aren't caught and handled, eg:

```
(node:8522) UnhandledPromiseRejectionWarning: RequestError: Error: connect ETIMEDOUT 52.57.118.192:8080
    at new RequestError (/home/steve/ewelink-api/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/home/steve/ewelink-api/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/steve/ewelink-api/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/steve/ewelink-api/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/steve/ewelink-api/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:8522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by bassamseif** [comment]
is there any way to share the devices on multiple accounts? that would help bypass the issue for the time being

**Comment by ttz642** [comment]
> is there any way to share the devices on multiple accounts? that would help bypass the issue for the time being

The errors I'm getting are when there's internet connection issues, dropped traffic, lost internet etc.

Having multiple accounts and shared devices won't help.

**Comment by bassamseif** [comment]
@ttz642 you're right, there's undoubtedly a need for a fix here. Do we know if the issue is coming from the api or the library?

**Comment by ttz642** [comment]
> @ttz642 you're right, there's undoubtedly a need for a fix here. Do we know if the issue is coming from the api or the library?

Not sure, going to update to the 2.0 release branch this week then I'll start investigating a bit more.

**Comment by BadCoder1337** [comment]
@bassamseif @ttz642 
When a eWeLink App with main account give access to bot account another App should be online and accept share request. Also ensure you're passing correct region to API constructor. Type definiton is incomplete.

**Comment by bassamseif** [comment]
@BadCoder1337 I've tried sharing devices between two accounts on different phones but it seems to get stuck on the same message even if both phones have the app open simultaneously on different accounts

**Comment by ttz642** [comment]
When a connection has been open for a long time, days or weeks the connection can get disconnected and then get logged out, by defining the connection as **var** rather than **const** it's easy to re-open the connection, I limit attempts to 3, ie:


```
    (async () => {
        var tries = 0;
        do {
            //login = await connection.getCredentials();    //.login() DEPRECATED
            state = await connection.setDevicePowerState(req.params.deviceid, req.params.switch);
            if(DEBUG){
                console.log("Switch",req.params.deviceid,"status:",JSON.stringify(state,null,4));
            }
            if(state.error == undefined){
                tries = 4;//done...
            }else{
                if(state.error == 401){
                    if(DEBUG){
                        console.log("Reconecting...");
                    }
                    tries++;
                    if(tries<3)connection = new ewelink(account);// reconnect to ITLEAD server
                }
            }
        }while(tries <= 3);//make 3 attempts to switch (including 2 reconnects)
    })();
```
