### ISSUE TITLE
It's possible to listen to an RF Bridge triggers?

### ISSUE THREAD

**Issue by andres934** [skydiver/ewelink-api#5]
I see the library can check Devices and change the state of them, but could be or it's possible to listen to an RF Bridge triggers? that would be definetly a game changer because it's not possible not event with IFTTT

**Comment by andres934** [comment]
After researching a little bit, i notice that the way this library is communicating with itead server is using a path, i found that there is a path for every type of device, so maybe using the path to a certain RF Bridge(Before getting the id of the device) it could be possible to listen to triggers registering a EventEmitter on that path so when there is a change it will notify, just giving some ideas because listening to RF Bridge without flashing is definetly a game changer

**Comment by frborda** [comment]
+1

**Comment by skydiver** [comment]
Hello @andres934 

One of the difficulties of this project is we need access to specific devices (sadly i have access to a few generic ones).

So, i think if this is possible, must be performed by someone with access to a RF Bridge device.

**Comment by andres934** [comment]
> Hello @andres934
> 
> One of the difficulties of this project is we need access to specific devices (sadly i have access to a few generic ones).
> 
> So, i think if this is possible, must be performed by someone with access to a RF Bridge device.

i understand, just consider the implementation with a RF Bridge in the future, because for sure, it will be a game changer, that single device is so important and is a complete headache to use it, the functionality it's too limited

**Comment by skydiver** [comment]
@andres934 & @frborda 

Version 1.6.0 includes a new method called `openWebSocket` which can be used to listen to realtime events.

Not sure if is the feature you where looking, but you can check the docs for more info.

https://ewelink-api.now.sh/docs/available-methods/openwebsocket

**Comment by thorito** [comment]
Do open sockets have a defined timeout?

After a time in execution, it stops receiving events, some idea ?

Note: I'm using version 1.8.0

Thank you
