### ISSUE TITLE
Please support mobile number login

### ISSUE THREAD

**Issue by shaonianzhentan** [skydiver/ewelink-api#50]
thank you

**Comment by shaonianzhentan** [comment]
const nonce = require('nonce')();

const { makeFakeIMEI } = require('../ewelink-helper');

const credentialsPayload = ({ email, password }) => {

  let body = {    
    password,
    version: 6,
    ts: `${Math.round(new Date().getTime() / 1000)}`,
    nonce: `${nonce()}`,
    appid: 'oeVkj2lYFGnJu5XUtWisfW4utiN4u9Mq',
    imei: makeFakeIMEI(),
    os: 'iOS',
    model: 'iPhone10,6',
    romVersion: '11.1.2',
    appVersion: '3.5.3',
  }

  // use phoneNumber field is ok
  // I want to change email to username
  if(email.includes('@')){
    body['email'] = email
  }else{
    body['phoneNumber'] = email
  }


  console.log(body)
  return body
};

module.exports = credentialsPayload;

**Comment by Leechael** [comment]
+1 for this, but the key name `phoneNumber` since incorrect.

**Comment by skydiver** [comment]
this was done on v3.0.0
