### ISSUE TITLE
connection.setDevicePowerState returns success but does not work

### ISSUE THREAD

**Issue by bassamseif** [skydiver/ewelink-api#51]
When I try using the `connection.setDevicePowerState` api to `on`/`off`/`toggle` it does return a success response with
```
{ status: 'ok', state: 'on' }
```

but no changes are done to the physical actual switch

**Note:** I tested this a couple of days ago with the same exact script it was working, the switch is working through the ewelink app and the software switch on it

**Comment by skydiver** [comment]
Hey @bassamseif 

Have you tried on a web or a node script?

**Comment by bassamseif** [comment]
@skydiver i was trying from a node script, i had to reset the switch in order for things to work out. closing this since the issue is not from the code
