### ISSUE TITLE
South Africa za issue - Error: getaddrinfo ENOTFOUND za-api.coolkit.cc

### ISSUE THREAD

**Issue by Uzziza** [skydiver/ewelink-api#53]
"RequestError: Error: getaddrinfo ENOTFOUND za-api.coolkit.cc za-api.coolkit.cc:8080"

**Comment by ttz642** [comment]
This is an invalid domain, I'm guessing you just put your country code for the region.

From the itlead support:
`https://support.itead.cc/support/discussions/topics/11000001238`
Only valid domains are:

If your location is in Asia:
`cn-long.coolkit.cc, cn-api.coolkit.cc, api.coolkit.cc.`
If your location is in EU:
`eu-long.coolkit.cc, eu-api.coolkit.cc, api.coolkit.cc.`
If your location is in Oceania:
`cn-long.coolkit.cc, cn-api.coolkit.cc, api.coolkit.cc.`
`eu-long.coolkit.cc, eu-api.coolkit.cc, api.coolkit.cc.`
If your location is North Ameria or South America:
`cn-long.coolkit.cc, cn-api.coolkit.cc, api.coolkit.cc.`

Try logging in with email & password, ie don't pass the region, see:

- [Class Instantiation](https://ewelink-api.now.sh/docs/class-instantiation)

and then getCredentials, see: 

- [getCredentials](https://ewelink-api.now.sh/docs/available-methods/getregion)

**Comment by Uzziza** [comment]
Thanks for the info, used the EU region and connected,
