### ISSUE TITLE
Sonoff RF Bridge

### ISSUE THREAD

**Issue by mrpoponz** [skydiver/ewelink-api#62]
Hi,

Has anyone got the RF bridge working with learned remotes?  Querying the device shows it's got no switches.

Thanks,

Paul

**Comment by coin9176** [comment]
It's a bit different, you have to make a webapi request with:
cmd and RFchannel
See example
[rf.js.txt](https://github.com/skydiver/ewelink-api/files/4058791/rf.js.txt)

**Comment by mrpoponz** [comment]
Thanks for the code.  It works very well.
