### ISSUE TITLE
switch to fahrenheit?

### ISSUE THREAD

**Issue by gmittica** [skydiver/ewelink-api#67]
Is not possible at the moment switch to fahrenheit mode for TH10/16 sensors, but it seems to be possible from mobile apps, so probably there's a param that could be added to get back temperature in fahrenheit instead of celsius?

**Comment by skydiver** [comment]
I wasn't able to see a connection from the app to ewelink servers when switching from C to F.

So, my guess is that the `temp units` setting just converts celsius to fahrenheit at app level.

Would be possible to create a method who just reads the sensor in C and converts to F.
