### ISSUE TITLE
Broken Links to Documentation

### ISSUE THREAD

**Issue by Peterkn2001** [skydiver/ewelink-api#79]
Hi, a fellow (also retired) skydiver here!

The correct path to your documentation is:
https://github.com/skydiver/ewelink-api/tree/master/docs

but its shown as this in a couple of different locations:
https://github.com/skydiver/ewelink-api/docs
which gives a 404 error.

The two locations I'm aware of are:
https://github.com/skydiver/ewelink-api
https://www.npmjs.com/package/ewelink-api

Also, your personal website:
https://skydiver.dev
has an expired certificate.

Blue skies!

Pete.

**Comment by skydiver** [comment]
Thanks @Peterkn2001 

Sorry for the delay on the reply ... fixed the broken link 

Thank you and blue skies for you too!
