### ISSUE TITLE
warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

### ISSUE THREAD

**Issue by xo555** [skydiver/ewelink-api#82]
Please kindly asking you to help me to use your app. For first time to install the ewelink-api on Node.js 12.16.2 (x64) I got this issue and so on:
warn deprecated request@2.88.2:
see the logs attached or link
https://drive.google.com/open?id=1RdjJI_8KTgY-HBs7kVfsp04O8SVyQX8I

Also please sorry I'm beginner any tutorial will be great

[_logs.zip](https://github.com/skydiver/ewelink-api/files/4535215/_logs.zip)

**Comment by skydiver** [comment]
thanks for the notice @xo555 

`request` library will be replaced with `node-fetch` on version 3.0
