### ISSUE TITLE
401 Authentication error with Phone Numbers

### ISSUE THREAD

**Issue by ameer1234567890** [skydiver/ewelink-api#83]
I am getting `401 Authentication error` with phone numbers as login email. I do use the country code and it gives `401` even for `getRegion` requests. I tried using another account with an email address and it works.

**Comment by ttz642** [comment]
Have you tried using the phone number to log in directly with the app on a mobile? Sounds more likely a problem with the server than ewelink-api.

**Comment by ameer1234567890** [comment]
Yes, I have tried and it works.

**Comment by skydiver** [comment]
hey @ameer1234567890 

i was trying to make this change but i wasn't able to test (cannot use phone with my account, looks like the phone is only available on China)

maybe i can make a branch so you can test locally ?

**Comment by ameer1234567890** [comment]
Yes please

**Comment by skydiver** [comment]
Hey @ameer1234567890 

In the next days version 3.0 will be release and adds support for login using phone number.

You can test this branch: `release/3.0.0`

Let me know if works for you.


Thanks.-

**Comment by ameer1234567890** [comment]
@skydiver I have tested and can confirm that `release/3.0.0` branch works for login using phone number. I specified phone number as `phoneNumber: '+9609977444'` where `+960` is the country code. I think it would be a better idea to make a note at `class-instantiation.md` to include country code as a prefix to phone number. Highly appreciated.

**Comment by skydiver** [comment]
Thanks for testing @ameer1234567890 

Here is the updated document: https://github.com/skydiver/ewelink-api/blob/668d60419d8aa12163372e3d7d79d97756bb2f97/docs/class-instantiation.md

Do you have any suggestion? Feel free to update the file.
