### ISSUE TITLE
Important Notification From SONOFF

### ISSUE THREAD

**Issue by Daniel-zhan-itead** [skydiver/ewelink-api#84]
As eWeLink will stop provide the support and maintance of current APPID & APP secret on Aug 31th 2020. 

That means that this project may work improperly.

eWeLink will offer a special APPID and APP secret for this project.

@skydiver  Please contact me via the mail 

To: daniel.zhan@itead.cc
and cc: jiale.liu@coolkit.cn

Daniel

**Comment by skydiver** [comment]
thanks @Daniel-zhan-itead 

fix included on next release #85
