### ISSUE TITLE
Not able to install on iobroker

### ISSUE THREAD

**Issue by ruhlandm1** [skydiver/ewelink-api#91]
Hello together,

I try to install it on the iobroker and get the following log:

$ ./iobroker url "https://github.com/skydiver/ewelink-api.git"
install https://github.com/skydiver/ewelink-api/tarball/c11b3a8ab706cabcb592b4f9799314405788b640
NPM version: 6.14.5
npm install https://github.com/skydiver/ewelink-api/tarball/c11b3a8ab706cabcb592b4f9799314405788b640 --loglevel error --prefix "/opt/iobroker" (System call)
ERROR: host.raspberrypi Cannot install https://github.com/skydiver/ewelink-api/tarball/c11b3a8ab706cabcb592b4f9799314405788b640: 0
ERROR: process exited with code 25

Something I can do about that?

**Comment by skydiver** [comment]
Hey @ruhlandm1 

Never used iobroker so i'm not sure what can be the problem.

I see they have a docker image, maybe it's a good place to try installing and see if they are errors too.
