### ISSUE TITLE
web socket question

### ISSUE THREAD

**Issue by bwp91** [skydiver/ewelink-api#92]
Hi,
Quick question.
Perhaps the answer won’t be so quick!

Is it possible to use this package to send a request via the websocket (instead of the http app) for example to switch on/off a device.

Thanks

**Comment by skydiver** [comment]
Hey @thepotterfamily 

Sure, you need to follow these instructions: https://github.com/skydiver/ewelink-api/blob/master/docs/available-methods/openwebsocket.md
