### ISSUE TITLE
Bad server whith region set to FR (France)

### ISSUE THREAD

**Issue by lbenech** [skydiver/ewelink-api#99]
When I use my FR (France) ewelink account with the ewelink-api (3.0.0), I get an http error because the API is looking for the server "fr-api.coolkit.cc" instead of the good one wich seems to be "eu-api.coolkit.cc" for european countries.

**Comment by skydiver** [comment]
Hello @lbenech 

Whats happens when you run this: https://github.com/skydiver/ewelink-api/blob/master/docs/available-methods/getregion.md ?
